[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.1", default-features = false, features = ['std'] }
utils = { path = "../../utils" }
sdk = { git = "https://github.com/Hyle-org/hyle.git", package = "hyle-contract-sdk" }
